### ISSUE TITLE
Benchmarks

### ISSUE THREAD

**Issue by chico-depressive** [smasherprog/rat_lite#72]
hi, thanks for this nice lib, do you have any information about benchmarks against other libs? how is it better or faster? any plans to add support for 1/2/4bit lossy/lossless compression?

**Comment by smasherprog** [comment]
I dont have any benchmarks, I am in the process of creating a test suite. Benchmarks for this would be difficult because of the number of things that attribute the overall performance: network library; image compression library; UI lIbrary; Screen Capturing Library; the Operating System... etc

Basically, my goal is to be able to capture my current setup: I have (3) 4k Screens and an i7 2600 and stream those using less than 5% cpu at 10-15fps. Bandwith is another issue because I only send Difs. So, if the screen never changes, no data is sent. But, I use lib jpeg turbo which is the best jpeg library.

I will add support for as many image formats that make sense for the purpose of a screen share application. For example, grayscale might make sense because it can be super compressed.

**Comment by chico-depressive** [comment]
@smasherprog ever considered using ffmpeg?

**Comment by chico-depressive** [comment]
another question, your library implements support for multiple desktops and window stations in windows OS?

**Comment by smasherprog** [comment]
I considered ffmpeg, but its for a different use-case.
ffmpeg is good for streaming images that are constantly changing -- like movies. If the stream doesn't change often --like a desktop-- then its not a good fit because it still streams data .. quite a bit too.
The method I use sends snippets of changes, and desktop images hardly change at all which leads to --in most cases-- a very very small amount of data sent. 
I can add 1/2/4/8 bit lossy compression.   The lowest I had thought was 8 bit grayscale, but I could goto 4 bit grayscale as well.

**Comment by smasherprog** [comment]
I allow the users to configure which desktops are captured
Multiple stations are going to come at a later point, it requires writing a service. Luckily I have that code from the last iteration which should be the same.
So, its not there yet but its coming.

**Comment by smasherprog** [comment]
The screen capturing code is in its own library https://github.com/smasherprog/Screen_Capture
In case you wanted to see how that works.

**Comment by chico-depressive** [comment]
@smasherprog cant wait for 4bit greyscale, thank you sir!

**Comment by chico-depressive** [comment]
@smasherprog any possibility to add 4bit greyscale lossy to v0.4 milestone?

**Comment by smasherprog** [comment]
I believe that libjpeg turbo only supports 8 bit grayscale.
https://github.com/libjpeg-turbo/libjpeg-turbo
